# Autogenerated wrapper script for Qt6Charts_jll for armv7l-linux-gnueabihf-cxx11
export libqt6charts, libqt6chartsqml

using Qt6Base_jll
using Qt6Declarative_jll
JLLWrappers.@generate_wrapper_header("Qt6Charts")
JLLWrappers.@declare_library_product(libqt6charts, "libQt6Charts.so.6")
JLLWrappers.@declare_library_product(libqt6chartsqml, "libQt6ChartsQml.so.6")
function __init__()
    JLLWrappers.@generate_init_header(Qt6Base_jll, Qt6Declarative_jll)
    JLLWrappers.@init_library_product(
        libqt6charts,
        "lib/libQt6Charts.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libqt6chartsqml,
        "lib/libQt6ChartsQml.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
